### ISSUE TITLE
h5browser log viewer not working

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#14]
![log_viewer](https://user-images.githubusercontent.com/5221986/66138371-ce78fc00-e5fe-11e9-90a5-e433087f381b.PNG)

I would expect some logs in the bottom right window

**Comment by seb5g** [comment]
As any data node in the tree, in order to see the data (log list, you have to double click on it)!

**Comment by quantumm** [comment]
First I do not understand what the 'Logger' node represents for a dataset. Is it supposed to save all the logs from every scans of the dataset ?
Whatever I do, double-clic on the Logger node or double-clic on a Scan node, nothing is displayed in the logger window. It even happen that the module crash if I double-clic on a Scan node.
I have to precise that this h5 file has been saved with the 1.5.1 version of pymodaq, and I now have the 1.6, I do not know if this is important…

**Comment by seb5g** [comment]
It is very important as the version 1.6 is the first to have a fully
concise way of saving attributes, which are needed by the h5 browser. Your
data can still be read but not properly displayed.
You could create an environment for the version 1.5 and 1.6 in order to
read your data properly.  As with the version 1.6 files will always be
saved with same attributes. See
http://pymodaq.cnrs.fr/usage/saving.html#from-daq-scan
Is issue 13 also related to same conditions?

**Comment by quantumm** [comment]
Yes issue 13 is related to same conditions
