### ISSUE TITLE
Frozen daq_scan during acquisition

### ISSUE THREAD

**Issue by NPy2020** [CEMES-CNRS/PyMoDAQ#54]
This issue is random in time and doesn't happen for each scan,  It can happen:
- after 60 points as well as after 500 points
- with a time flow of 100 + 100ms (time step + time between) or with a time flow of 500 + 5500ms
- in my "measurement" preset which contains 3 plugins (vna, lockin move V and lockin viewer) and in my "calibration" preset which contains two other plugins (lockin move H and lakeshore).

In the log there is no error or message when this occurs, the Daq_Scan is just stopped and seems to be waiting for the measurement. The move led is green because the step is finished and the detection led is red because the value is not detected by the daq_scan. Everything is frozen. 
Two observations:
- If I click on "probe's data acquisition" in the daq_scan, it takes the value of the point of the current scan then move the next step and waits again for the next acquisition.
- If I click on "single grab" in the dashboard on the viewer plugin for the signal being acquired, the scan is running again and ends the remaining points normally.

By the way, I have also noticed that for each step of the move plugin, the program sends the "check_position" request three times to which the instrument returns three identical responses.

**Comment by NPy2020** [comment]
We found the origin of this issue and find a simple solution by the plugin way, even a solution in the PyMoDAQ structure will be better.
The issue appear with a dual detector scanning (2D scan). Sometimes the two answers comes at the same time from the two detectors make a mistakes between them and PyMoDAQ loose one of them. 
![image](https://user-images.githubusercontent.com/83576939/145032567-bc42fb6f-970d-4d54-9731-1abbdc2e5506.png)

With somme nice print() we are able to found that the values read at this time is a numpy.array with “None” inside .
![image](https://user-images.githubusercontent.com/83576939/145029406-0bf1e0aa-79f0-424e-a954-26d7ab5bd867.png)

The scan freeze and wait for the good value. 
We can continue the scan with a simple clic on “snapshot” a single grab on the dashboard. With this value the Daq_scan become happy and continue with the next step.

The solution we found is to add a condition in our plugin in the “grab data” to say : if the measure is “None” do a single grab in both plugin of the concerned detectors : 
from pymodaq.daq_viewer.daq_viewer_main import DAQ_Detector as daqdetector
![image](https://user-images.githubusercontent.com/83576939/145030240-de27fada-788d-4e37-92b8-9f12dc8449bb.png)

For one the import of the DAQ_Detector is not possible at the top of one plugin (it will crached the dashboard init) so we import it when the wrong way appear.
![image](https://user-images.githubusercontent.com/83576939/145030488-511c3180-b2c7-4a5d-aefc-afe7671d6164.png)

Now when the mistakes comes the scan continue with the next step automatically and we can count the error of acquisition ^^. The long automatic acquisition is possible.
#

**Comment by seb5g** [comment]
The way you did is wrong because DAQ_Detector is an object that must be instantiated. You could do it it self was an instance of DAQ_Detector, but it isn't. Self is an instance of your plugin. 

The real issue must be the order in which the communication is made with the instrument. if multiple plugins want to access the hardware at the same time using serial com, maybe there is some ordering issues sometimes. You can ovoid it using the locker primitive of the thread module within the wrapper communicating with your instrument

![image](https://user-images.githubusercontent.com/6609955/145035536-5fe00ec2-fc26-457e-8bd7-ec5d7d3834cd.png)

and then when you need to talk with the instrument, you first *acquire* the lock (other thread cannot communicate anymore and are in a waiting state) and finally *release* it when done, so that other threads can communicate.
![image](https://user-images.githubusercontent.com/6609955/145035826-7972f6af-3faa-4c1b-b9dc-cf898a7c400e.png)

**Comment by NPy2020** [comment]
Thanks for this good way solution.
