### ISSUE TITLE
Dask is a quite heavy dependence that does not seem to be really used by PyMoDAQ

### ISSUE THREAD

**Issue by davidtrem** [CEMES-CNRS/PyMoDAQ#6]
Dask is in setup.py dependencies while dask seems to be used only in /pymodaq/daq_utils/plotting/viewerND/signal.py 
```python
@data.setter
    def data(self, value):
        from dask.array import Array
        if isinstance(value, Array):
            if not value.ndim:
                value = value.reshape((1,))
            self._data = value
        else:
            self._data = np.atleast_1d(np.asanyarray(value))
```

Yet, it looks strange that some dask Array could appear here...
Couldn't the Dask specific code be removed ?
At least, if this dask specific code is really required, I guess Dask should
still be removed from setup.py dependencies and this Dask specific code
could be included in a try / except statement to cover the case
where dask is not installed (?)

**Comment by seb5g** [comment]
I wrote this code from bits of a larger library: hyperspy. I already removed many of the heavy stuff that were mandatory from there. It's very possible dask is not really needed and I invite you to try it out :-)

in pymodaq, viewerND is just used (for the moment) within the h5Browser, in order to view data that have dimensionality 0, 1, 2 , 3 or 4 
Let me know!!

**Comment by davidtrem** [comment]
Ok. Then for sure dask is not a requirement. I'll come up with other pull requests...

**Comment by seb5g** [comment]
I accepted your pull requests conerning this issue. I now close it
